
language: node_js
node_js: stable
git:
  depth: false
branches:
  only:
    - development

# S: Build Lifecycle
install:
  - yarn

script:
  - yarn build

after_success:
  - cd ./vuepress/dist
  - echo ${GH_CNAME} > CNAME
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git add .
  - git commit -m "Build $(date +%Y%m%d%H%M)"
  - git push --force "https://${GH_TOKEN}@${GH_REPO}" master:master
# E: Build LifeCycle