
language: node_js
node_js: stable
git:
  depth: false
branches:
  only:
    - development

# S: Build Lifecycle
install:
  - yarn install -g vuepress

script:
  - yarn build

cache:
  directories:
    - "node_modules"
    
notifications:
  email: false
  
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: src/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: fen89/fen89.github.io
  keep-history: true
  target-branch: master
  on:
    branch: development
